export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const FETCH_MOVIE = "FETCH_MOVIE"
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS"
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE"

export const FETCH_MOVIE_DETAILS_FAILURE = "FETCH_MOVIE_DETAILS_FAILURE"
export const FETCH_MOVIE_DETAILS_SUCCESS = "FETCH_MOVIE_DETAILS_SUCCESS"
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS"
